= AsciiDoc Docstyle Skins
Asciidoctor Skins Project
:icons: font
:stylesheet: ./document/document.css
:linkcss:

This is a collection of pre-made Asciidoctor style templates for different types of documents. The core styles are based on https://github.com/Mogztter/asciidoctor-web-pdf[asciidoctor-web-pdf,window=_blank] by @Mogztter, but contributions adding docstyles for other types of documents are welcome! This page uses the basic Document style, which can be viewed link:document/[here,window=_blank].

== Available Styles

* link:book/[Book,window=_blank] (https://raw.githubusercontent.com/dohliam/asciidoctor-skins/docstyles-testing/docstyles/book/book.adoc[Source,window=_blank])
* link:cheatsheet/[Cheatsheet,window=_blank] (https://raw.githubusercontent.com/dohliam/asciidoctor-skins/docstyles-testing/docstyles/cheatsheet/cheatsheet.adoc[Source,window=_blank])
* link:document/[Document,window=_blank] (https://raw.githubusercontent.com/dohliam/asciidoctor-skins/docstyles-testing/docstyles/document/document.adoc[Source,window=_blank])
* link:letter/[Letter,window=_blank] (https://raw.githubusercontent.com/dohliam/asciidoctor-skins/docstyles-testing/docstyles/letter/letter.adoc[Source,window=_blank])
* link:presentation/[Presentation,window=_blank] (https://raw.githubusercontent.com/dohliam/asciidoctor-skins/docstyles-testing/docstyles/presentation/presentation.adoc[Source,window=_blank])
* link:resume/[Resume,window=_blank] (https://raw.githubusercontent.com/dohliam/asciidoctor-skins/docstyles-testing/docstyles/resume/resume.adoc[Source,window=_blank])
* link:storybook/[Storybook,window=_blank] (https://raw.githubusercontent.com/dohliam/asciidoctor-skins/docstyles-testing/docstyles/storybook/storybook.adoc[Source,window=_blank])

== Bookmarklet

Click or drag +++<a href="javascript:(function()%7Bvar%20body%20%3D%20document.getElementsByTagName('body')%5B0%5D%3Bscript%20%3D%20document.createElement('script')%3Bscript.type%3D%20'text%2Fjavascript'%3Bscript.src%3D%20'https%3A%2F%2Fdohliam.github.io%2Fasciidoctor-skins%2F%2Fdocstyles%2Fswitcher.js'%3Bbody.appendChild(script)%7D)()">this bookmarklet</a>+++ to your bookmark bar to preview these docstyles on any rendered Asciidoctor document.

++++
<script src="./document/paged.polyfill.min.js"></script>
++++
